/* Generated By:JavaCC: Do not edit this line. LovelaceConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LovelaceConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int LET = 6;
  /** RegularExpression Id. */
  int APAR = 7;
  /** RegularExpression Id. */
  int FPAR = 8;
  /** RegularExpression Id. */
  int BEGIN = 9;
  /** RegularExpression Id. */
  int END = 10;
  /** RegularExpression Id. */
  int FLINE = 11;
  /** RegularExpression Id. */
  int ATRB = 12;
  /** RegularExpression Id. */
  int FLOAT = 13;
  /** RegularExpression Id. */
  int BOOL = 14;
  /** RegularExpression Id. */
  int VOID = 15;
  /** RegularExpression Id. */
  int PRINT = 16;
  /** RegularExpression Id. */
  int SUM = 17;
  /** RegularExpression Id. */
  int SUB = 18;
  /** RegularExpression Id. */
  int MUL = 19;
  /** RegularExpression Id. */
  int DIV = 20;
  /** RegularExpression Id. */
  int AND = 21;
  /** RegularExpression Id. */
  int OR = 22;
  /** RegularExpression Id. */
  int LESS = 23;
  /** RegularExpression Id. */
  int GREATHER = 24;
  /** RegularExpression Id. */
  int EQUAL = 25;
  /** RegularExpression Id. */
  int IF = 26;
  /** RegularExpression Id. */
  int WHILE = 27;
  /** RegularExpression Id. */
  int RETURN = 28;
  /** RegularExpression Id. */
  int TRUE = 29;
  /** RegularExpression Id. */
  int FALSE = 30;
  /** RegularExpression Id. */
  int VIRG = 31;
  /** RegularExpression Id. */
  int DEF = 32;
  /** RegularExpression Id. */
  int NUM = 33;
  /** RegularExpression Id. */
  int ID = 34;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"main\"",
    "\"let\"",
    "\"(\"",
    "\")\"",
    "\"begin\"",
    "\"end\"",
    "\";\"",
    "\":=\"",
    "\"Float\"",
    "\"Bool\"",
    "\"Void\"",
    "\"print\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&&\"",
    "\"||\"",
    "\"<\"",
    "\">\"",
    "\"==\"",
    "\"if\"",
    "\"while\"",
    "\"return\"",
    "\"true\"",
    "\"false\"",
    "\",\"",
    "\"def\"",
    "<NUM>",
    "<ID>",
  };

}
